name = "MyPkg"
uuid = "2a74e58f-679f-4a9f-958d-7b7cf6fec4cf"
authors = ["migue <miguescobarm@gmail.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
LinearAlgebra = "1.10.0"
StaticArrays = "1.9.10"
