name: Run Benchmarks

on:
  pull_request:
    branches:
      - main
    paths:
      - 'src/**'
      - 'benchmarks/**'

  # Trigger after the completion of the Tests workflow
  workflow_run:
    workflows: ["Tests"]
    types:
      - completed

permissions:
  contents: write
  statuses: read
  deployments: write
  pull-requests: write

jobs:
  benchmark:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Julia
      - name: Set up Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: '1.11'

      # Step 3: Add and Instantiate Dependencies
      - name: Install dependencies
        run: |
          julia --project=. -e '
          using Pkg;
          Pkg.add("BenchmarkTools");
          Pkg.instantiate();
          Pkg.resolve();'

      # Step 4: Run the benchmark script
      - name: Run benchmarks
        run: |
          julia benchmarks/benchmark.jl
        env:
          JULIA_PROJECT: .

      # Step 5: Upload benchmark results using github-action-benchmark
      - name: Upload Benchmark Results
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: Julia benchmark result
          tool: 'julia'
          output-file-path: benchmarks/benchmark_results.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
          alert-threshold: '2000%'
          comment-on-alert: true
          fail-on-alert: true

      # Step 6: Upload the benchmark results as a check on GitHub
      - name: Upload benchmark results to GitHub
        uses: actions/upload-artifact@v3
        with:
          name: benchmark-results
          path: benchmarks/benchmark_results.json
