name: Benchmarks

permissions:
  contents: write # Required to update benchmark results
  pull-requests: write # Required to comment on pull requests

on:
  pull_request:
    branches:
      - main
    paths:
      - "src/**/*"
      - "benchmarks/**/*"
      - "Project.toml"
      - ".github/workflows/benchmark.yml"
  push:
    branches:
      - main
    paths:
      - "src/**/*"
      - "benchmarks/**/*"
      - "Project.toml"
      - ".github/workflows/benchmark.yml"

jobs:
  benchmark:
    if: ${{ !contains(github.event.head_commit.message, '[skip benchmarks]') }}
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Julia
      - name: Set up Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: '1.11' # Replace with your required Julia version

      # Step 3: Install dependencies
      - name: Install Julia dependencies
        run: |
          julia -e 'using Pkg; Pkg.instantiate(); Pkg.add("BenchmarkTools"); Pkg.add("JSON")'

      # Step 4: Run & upload benchmarks
      - name: Run benchmarks
        uses: benchmark-action/github-action-benchmark@v1
        with:
          tool: 'julia'
          output-file-path: benchmarks/benchmark_results.json
          benchmark-data-dir-path: benchmarks
          github-token: ${{ secrets.GITHUB_TOKEN }}
          comment-always: true
          summary-always: true
          alert-threshold: "150%"
          fail-on-alert: false
          auto-push: ${{ github.event_name != 'pull_request' }}