name: Run Benchmarks

on:
  pull_request:
    branches:
      - main
  workflow_run:
    workflows: [Run Tests]
    types: [completed]

permissions:
  contents: write
  statuses: read
  deployments: write
  pull-requests: write

jobs:
  benchmark:
    runs-on: ubuntu-latest

    #  if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Log workflow info
        run: |
          echo "Workflow: Tests"
          echo "Status: ${{ github.event.workflow_run.conclusion }}"

      # Step 1: Check out the repository
      - name: Check out the repository
        uses: actions/checkout@v4

      # Step 2: Set up Julia
      - name: Set up Julia
        uses: julia-actions/setup-julia@v2
        with:
          version: '1.10'

      # Step 3: Install dependencies and dev MyPkg in benchmarks environment
      - name: Install dependencies
        run: |
          julia --project=benchmarks -e '
          using Pkg
          Pkg.develop([ # dev MyPkg
            PackageSpec(path=pwd(), subdir=".")
          ])
          Pkg.instantiate()'

      # Step 4: Run the benchmarks
      - name: Run benchmarks
        run: |
          julia --project=benchmarks benchmarks/benchmark.jl

      # Step 5: Upload benchmark results using github-action-benchmark
      - name: Upload Benchmark Results
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: Julia benchmark result
          tool: 'julia'
          output-file-path: benchmarks/benchmark_results.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
          comment-on-alert: true
          fail-on-alert: true

      # Step 6: Upload the benchmark results as a check on GitHub
      - name: Upload benchmark results to GitHub
        uses: actions/upload-artifact@v3
        with:
          name: benchmark-results
          path: benchmarks/benchmark_results.json
