name: Benchmark PR

on:
  pull_request:
    branches:
      - main

jobs:
  benchmark:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Julia
        uses: julia-actions/setup-julia@v1

      - name: Install dependencies
        run: |
          julia -e 'using Pkg; Pkg.add("BenchmarkTools")'

      - name: Run benchmarks
        run: |
          julia -e 'using BenchmarkTools; include("scripts/benchmark.jl")'

      - name: Commit leaderboard update
        run: |
          # Get the PR number and execution time from the results
          PR_NUMBER=$(jq -r '.pull_request.number' "$GITHUB_EVENT_PATH")
          EXECUTION_TIME=$(jq -r '.benchmark_results[0].time' results/results.json)

          # Append benchmark result to leaderboard.md
          echo "| PR #$PR_NUMBER | $EXECUTION_TIME |" >> leaderboard.md

          # Commit the updated leaderboard.md
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add leaderboard.md
          git commit -m "Update leaderboard with PR #$PR_NUMBER benchmark"
          git push

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RESULTS_FILE: results/results.json
