name: Tests

# on:
#   push:
#     branches:
#       - main
#   pull_request:
#     branches:
#       - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: '1.10' # Julia versions
        arch: [x64]     # Architecture

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Julia
        uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}

      - name: Cache artifacts
        uses: actions/cache@v4
        with:
          path: ~/.julia/artifacts
          key: ${{ runner.os }}-test-artifacts-${{ matrix.version }}-${{ hashFiles('**/Project.toml') }}
          restore-keys: |
            ${{ runner.os }}-test-artifacts-${{ matrix.version }}-
            ${{ runner.os }}-test-artifacts-

      - name: Cache compiled packages
        uses: actions/cache@v4
        with:
          path: ~/.julia/compiled
          key: ${{ runner.os }}-test-compiled-${{ matrix.version }}
          restore-keys: |
            ${{ runner.os }}-test-compiled-

      - name: Run tests
        uses: julia-actions/julia-runtest@v1
